@startuml
'https://plantuml.com/class-diagram

class ToDoList{
    + main()
    + start()
}

class HelpPageController {
    + backButtonClicked
}

class ExpandItemController {
    + backButtonClicked
}

class ToDoListController{
    - ToDoListTableview
    - ItemName: TextField
    - DueDate: TextField
    - ItemDescription: TextField
    - ItemStatus: TextField

    + clearList
    + expandItem
    + addNewItemButtonClicked
    + exportListButtonClicked
    + loadListButtonClicked
    + displayAllItemsButtonClicked
    + displayCompletedItemsButtonClicked
    + displayIncompleteItemsButtonClicked
    + deleteItemButtonClicked
    + helpButtonClicked
}



javafx.ToDoList <-> javafx.HelpPage
javafx.ExpandItem <-> javafx.ToDoList
javafx.ToDoList <|-- ToDoList
javafx.HelpPage -- HelpPageController
javafx.ExpandItem -- ExpandItemController

ToDoList -- ToDoListController

@enduml